spring.application.name=bracketgen
spring.datasource.url=jdbc:postgresql://localhost:5432/Tournament
spring.datasource.username=edgarrd11
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.driver-class-name=org.postgresql.Driver